
import java.awt.Color;
import java.sql.*;
import java.awt.Font;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class checkProgress extends javax.swing.JFrame {

    /**
     * Creates new form checkProgress
     */
   
   
    String hyprlinkText ="<HTML><b><u> <i>See FIR Copy</i></u></b></HTML>";
    public checkProgress() {

        initComponents();
        searchButton.setBackground(Color.WHITE);
        progressButton.setBackground(Color.WHITE);
        this.setTitle("Check Report Progress");
        Image icon = new ImageIcon(this.getClass().getResource("/project_icon.png")).getImage();
        this.setIconImage(icon);
        
        percantageLabel.setVisible(false);
        progressPanel.setVisible(false);
        notFoundLabel.setVisible(false);
        progressButton.setEnabled(false);
        
        investigationLabel.setVisible(false);
        FIRLabel.setVisible(false);
        seeFIRcopyLabel.setVisible(false);
        evidenceLabel.setVisible(false);
        suspectLocatedLabel.setVisible(false);
        suspectConfessedLabel.setVisible(false);
        suspectLocatedLabel.setVisible(false);
        victimFoundLabel.setVisible(false);
        
        seeDetailedReportPanel.setVisible(false);
    }
    
    public void ShowProgress(int id){
         try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/crime record", "root", "");
                PreparedStatement pst = con.prepareStatement("select id,investigationStarted,createFIR,evidenceCollected,"
                        + "suspectLocated,suspectConfessed,victimFound,userid,consentRequested,consentGiven from progress where id=?");
                
                pst.setInt(1, id);
                ResultSet rs=pst.executeQuery();
                
               while(rs.next()){
                    if(rs.getString("investigationStarted").equals("y")){
                        investigationLabel.setVisible(true);
                    }
                    
                    if(rs.getString("createFIR").equals("y")){
                        FIRLabel.setVisible(true);
                        seeFIRcopyLabel.setVisible(true);
                        seeFIRcopyLabel.setText(hyprlinkText);
                        seeFIRcopyLabel.setForeground(new Color(51,51,255));
                    }
                    if(rs.getString("evidenceCollected").equals("y")){
                        evidenceLabel.setVisible(true);
                    }
                    if(rs.getString("suspectLocated").equals("y")){
                        suspectLocatedLabel.setVisible(true);
                    } 
                    if(rs.getString("suspectconfessed").equals("y")){
                        suspectConfessedLabel.setVisible(true);
                    } 
                    if(rs.getString("victimFound").equals("y")){
                        victimFoundLabel.setVisible(true);
                    }
                    if(rs.getString("consentRequested").equals("y")){
                        if(rs.getString("consentGiven").equals("n")){
                            int x = JOptionPane.showConfirmDialog(null, "Admin requests your consent for creating FIR on this report.\n"
                                + "Do you give your consent?", "Select", JOptionPane.YES_NO_OPTION);
                            if(x==0){
                                try {
                                    String s="y";
                                    Statement st = con.createStatement();

                                    st.executeUpdate("  UPDATE progress SET consentGiven='"+s+"' WHERE id='"+id+"'   ");
                                    JOptionPane.showMessageDialog(this, "Consent for creating FIR has been provided to the admin.\nYou will soon have an update.");
                                    } catch (Exception e) {
                                }
                            }
                        }
                    }
                   
                }    
                  
                } catch (Exception e) {
                }
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        reportIDtxt = new javax.swing.JTextField();
        progressButton = new javax.swing.JButton();
        progressPanel = new CustomPanel();
        jLabel2 = new javax.swing.JLabel();
        victimTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        crimeTypeTxt = new javax.swing.JTextField();
        dateTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        notFoundLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        investigationLabel = new javax.swing.JLabel();
        evidenceLabel = new javax.swing.JLabel();
        percantageLabel = new javax.swing.JLabel();
        FIRLabel = new javax.swing.JLabel();
        suspectLocatedLabel = new javax.swing.JLabel();
        suspectConfessedLabel = new javax.swing.JLabel();
        victimFoundLabel = new javax.swing.JLabel();
        seeDetailedReportPanel = new javax.swing.JPanel();
        seeDetailedReportLabel = new javax.swing.JLabel();
        seeFIRcopyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Report ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 22, -1, -1));

        reportIDtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportIDtxtMouseEntered(evt);
            }
        });
        jPanel1.add(reportIDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 19, 115, -1));

        progressButton.setText("See Progress");
        progressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressButtonActionPerformed(evt);
            }
        });
        jPanel1.add(progressButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 160, -1));

        progressPanel.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout progressPanelLayout = new javax.swing.GroupLayout(progressPanel);
        progressPanel.setLayout(progressPanelLayout);
        progressPanelLayout.setHorizontalGroup(
            progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );
        progressPanelLayout.setVerticalGroup(
            progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );

        jPanel1.add(progressPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 216, -1, -1));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel2.setText("Victim");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        jPanel1.add(victimTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 115, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel3.setText("Crime Type");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));
        jPanel1.add(crimeTypeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 170, -1));
        jPanel1.add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 130, -1));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel4.setText("Report Filed On");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        notFoundLabel.setBackground(new java.awt.Color(255, 0, 51));
        notFoundLabel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        notFoundLabel.setText("Report Not Found");
        jPanel1.add(notFoundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 61, -1, -1));

        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 18, 88, -1));

        investigationLabel.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        investigationLabel.setText("An admin has started looking in to your report");
        jPanel1.add(investigationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 214, -1, -1));

        evidenceLabel.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        evidenceLabel.setText("Evidence is being collected on the basis of your complaint");
        jPanel1.add(evidenceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 288, -1, -1));

        percantageLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        percantageLabel.setForeground(new java.awt.Color(64, 136, 96));
        percantageLabel.setText("percantageLabel");
        jPanel1.add(percantageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 483, -1, -1));

        FIRLabel.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        FIRLabel.setText("An FIR has also been created for your report.");
        jPanel1.add(FIRLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 251, -1, -1));

        suspectLocatedLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        suspectLocatedLabel.setForeground(new java.awt.Color(255, 0, 0));
        suspectLocatedLabel.setText("Suspect located!");
        jPanel1.add(suspectLocatedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 325, -1, -1));

        suspectConfessedLabel.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        suspectConfessedLabel.setText("Suspect has confessed to your allegation!!");
        jPanel1.add(suspectConfessedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 368, -1, -1));

        victimFoundLabel.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        victimFoundLabel.setForeground(new java.awt.Color(255, 51, 51));
        victimFoundLabel.setText("Victim is FOUND!!");
        jPanel1.add(victimFoundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 405, -1, -1));

        seeDetailedReportPanel.setBackground(new java.awt.Color(204, 204, 255));
        seeDetailedReportPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seeDetailedReportPanelMouseClicked(evt);
            }
        });

        seeDetailedReportLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        seeDetailedReportLabel.setText("See Detailed Report ");

        javax.swing.GroupLayout seeDetailedReportPanelLayout = new javax.swing.GroupLayout(seeDetailedReportPanel);
        seeDetailedReportPanel.setLayout(seeDetailedReportPanelLayout);
        seeDetailedReportPanelLayout.setHorizontalGroup(
            seeDetailedReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seeDetailedReportPanelLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(seeDetailedReportLabel)
                .addGap(26, 26, 26))
        );
        seeDetailedReportPanelLayout.setVerticalGroup(
            seeDetailedReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seeDetailedReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seeDetailedReportLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(seeDetailedReportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 534, -1, -1));

        seeFIRcopyLabel.setBackground(new java.awt.Color(255, 255, 255));
        seeFIRcopyLabel.setForeground(new java.awt.Color(51, 51, 255));
        seeFIRcopyLabel.setText("See FIR Copy");
        seeFIRcopyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seeFIRcopyLabelMouseClicked(evt);
            }
        });
        jPanel1.add(seeFIRcopyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 252, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void progressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressButtonActionPerformed
        String ID =reportIDtxt.getText();
        int id = Integer.parseInt(ID);
        
        
        int percantage=0;
        percantageLabel.setText("Investigation on your report has not been processed yet.");
        //we will check the progress table for showing a percantage 
        try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/crime record", "root", "");
                PreparedStatement pst = con.prepareStatement("select id,investigationStarted,createFIR,evidenceCollected,"
                        + "suspectLocated,victimFound,suspectConfessed,userid from progress where id=? ");
                
                pst.setInt(1, id);
                ResultSet rs=pst.executeQuery();
                
                //here no need to check for if currentUserId==reportFiledbyID or not
                //beacuse this will already be checked by the search button action
                //and the progress button wil only be activated if currentUserId==reportFiledbyID is verified from search button action performed
                while(rs.next()){
                    if(rs.getString("investigationStarted").equals("y")){
                        percantage=20;
                        percantageLabel.setText("Investigation on your report is completed by 20%.");
                    }
                    if(rs.getString("createFIR").equals("y")){
                        percantage=40;
                        percantageLabel.setText("Investigation on your report is completed by 40%");
                    }
                    if(rs.getString("evidenceCollected").equals("y")){
                        percantage=50;
                        percantageLabel.setText("Investigation on your report is completed by 50%");
                    }
                    if(rs.getString("suspectLocated").equals("y")){
                        percantage=75;
                        percantageLabel.setText("Investigation on your report is completed by 75%");
                    }
                    if(rs.getString("VictimFound").equals("y")){
                        percantage=90;
                        percantageLabel.setText("Investigation on your report is completed by 90%");
                    }
                    if(rs.getString("suspectConfessed").equals("y")){
                        percantage=100;
                        percantageLabel.setText("Investigation on your report is completed.");
                        seeDetailedReportPanel.setVisible(true);
                    }
                }
        } catch (Exception e) {
        }
        
        final int p = percantage;
        
        new Thread(new Runnable() {
             @Override
             public void run() {
                 progressPanel.setVisible(true);
                 for(int i=1;i<=p;i++){
             
                    try {
                        progressPanel.updateProgress(i);
                        progressPanel.repaint();
                        Thread.sleep(10);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(checkProgress.class.getName()).log(Level.SEVERE, null, ex);
                    }
              
                }
            }
         }).start();
        
        percantageLabel.setVisible(true);
        
        //bringing progress info from database table progress
        ShowProgress(id);
   
        progressButton.setEnabled(false);
    }//GEN-LAST:event_progressButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/crime record", "root", "");
            PreparedStatement pst = con.prepareStatement("select * from report where id=? ");
            
            int id = Integer.parseInt(reportIDtxt.getText());
            pst.setInt(1, id);
            ResultSet rs = pst.executeQuery();
                
           if(rs.next()==false){
               //means this record is not present in the entire database
              notFoundLabel.setVisible(true);
              progressButton.setEnabled(false);
              progressPanel.setVisible(false);
              
              victimTxt.setText("");
              crimeTypeTxt.setText("");
              dateTxt.setText("");
              }
           else{
                //means this record is present in the database
               
              
               
               int currentUserId=UserWindow.userid;
               int reportFiledById=Integer.parseInt(rs.getString("userid"));
               
               //this is for preventing one user to see other users' report
               if(currentUserId==reportFiledById){
                   //the record is present in the database
                   //and the record being searched was also filed by the searcher
                   notFoundLabel.setVisible(false);
                   progressButton.setEnabled(true);
                   progressPanel.setVisible(false);
                   
                    String v = rs.getString("victim");
                    victimTxt.setText(v);
                    victimTxt.setEditable(false);
                    String type = rs.getString("crimeType");
                    crimeTypeTxt.setText(type);
                    crimeTypeTxt.setEditable(false);
                    dateTxt.setText(rs.getString("reportFiledOn"));
                    dateTxt.setEditable(false);
               }
               else{
                   //the record is present in the database
                   //but the record being searched was not filed by the searcher
                    notFoundLabel.setVisible(true);
                    progressButton.setEnabled(false);
                    progressPanel.setVisible(false);
                    
                    victimTxt.setText("");
                    crimeTypeTxt.setText("");
                    dateTxt.setText("");
               }
               
           }           
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void reportIDtxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportIDtxtMouseEntered

        notFoundLabel.setVisible(false);
        progressButton.setEnabled(false);
        progressPanel.setVisible(false);
        seeDetailedReportPanel.setVisible(false);
        
        investigationLabel.setVisible(false);
        FIRLabel.setVisible(false);
        seeFIRcopyLabel.setVisible(false);
        evidenceLabel.setVisible(false);
        suspectLocatedLabel.setVisible(false);
        suspectConfessedLabel.setVisible(false);
        victimFoundLabel.setVisible(false);
        
        
        percantageLabel.setVisible(false);
    }//GEN-LAST:event_reportIDtxtMouseEntered

    private void seeDetailedReportPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeDetailedReportPanelMouseClicked
       seeDetailedReportLabel.setForeground(new java.awt.Color(255,255,255));
       
       seeDetailedReport.id=reportIDtxt.getText();
       new seeDetailedReport().setVisible(true);
    }//GEN-LAST:event_seeDetailedReportPanelMouseClicked

    private void seeFIRcopyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeFIRcopyLabelMouseClicked
        // TODO add your handling code here:
        seeFIRcopyLabel.setForeground(new java.awt.Color(255,0,255));
        
        String id = reportIDtxt.getText();
        seeFIRcopy.id=id;
        new seeFIRcopy().setVisible(true);
    }//GEN-LAST:event_seeFIRcopyLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkProgress().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FIRLabel;
    private javax.swing.JTextField crimeTypeTxt;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JLabel evidenceLabel;
    private javax.swing.JLabel investigationLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel notFoundLabel;
    private javax.swing.JLabel percantageLabel;
    private javax.swing.JButton progressButton;
    private CustomPanel progressPanel;
    private javax.swing.JTextField reportIDtxt;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel seeDetailedReportLabel;
    private javax.swing.JPanel seeDetailedReportPanel;
    private javax.swing.JLabel seeFIRcopyLabel;
    private javax.swing.JLabel suspectConfessedLabel;
    private javax.swing.JLabel suspectLocatedLabel;
    private javax.swing.JLabel victimFoundLabel;
    private javax.swing.JTextField victimTxt;
    // End of variables declaration//GEN-END:variables
}
