
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class createInvesitgationReport extends javax.swing.JFrame {

    /**
     * Creates new form createInvesitgationReport
     */
    public static int id;
    String name,age,profession,type,imageLocation,mattersToBeInvestigated,factsOfTheCase,invesitgationFindings;
    String txt1="To determine the sorrounding circumstances regarding the complaint filed from the user.";
    String txt2="To possibly identify the suspects that will lead to their aprehension and possible prosecuton.";
    String txt3="Description/occurrence & events of the crime reported";
    String txt4="Tracing info/confession of the suspect, Location info of victim(if missing) etc.";
    String defaultInvestigationText="";
    String defaultFactsText="";
    public createInvesitgationReport() {
        initComponents();
        mattersToBeInvestigatedTxt.setVisible(false);
        factsOfTheCaseTxt.setVisible(false);
        
        investigationFindingsTxt.setVisible(false);
        Show(id);
        
        this.setTitle("Creating Investigation Report");
        Image icon = new ImageIcon(this.getClass().getResource("/project_icon.png")).getImage();
        this.setIconImage(icon);
    }

    public void Show(int id){
        matters1.setText(txt1);
        matters2.setText(txt2);
        facts.setText(txt3);
        findings.setText(txt4);
        idTxt.setText(String.valueOf(id));
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/crime record", "root", "");
            PreparedStatement pst = con.prepareStatement("select * from report  where id=?");
            pst.setInt(1, id);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                name=rs.getString("victim");
                nameTxt.setText(name);
                age = rs.getString("victimAge");
                ageTxt.setText(age);
                profession = rs.getString("profession");
                profTxt.setText(profession);
                type = rs.getString("crimeType");
                crimeTypeTxt.setText(type);
                defaultFactsText=rs.getString("description");
                if(rs.getString("witnessPresent").equals("y"))
                    defaultFactsText+="\n An witness is present in the case, named " + rs.getString("witness")+ "." + "\n" + "Witness states that " + rs.getString("witnessStatement") + ".";
                
                imageLocation = rs.getString("victimImage");
                
                Image getAbsolutePath = null;
                ImageIcon icon = new ImageIcon(imageLocation);
                Image image = icon.getImage().getScaledInstance(victimImageLabel.getWidth(), victimImageLabel.getHeight(), Image.SCALE_SMOOTH);
                victimImageLabel.setIcon(icon);
            }
        } catch (Exception e) {
        }
        
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/crime record", "root", "");
            PreparedStatement pst = con.prepareStatement("select * from investigation  where id=?");
            pst.setInt(1, id);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                defaultInvestigationText = "Suspect was located from " + rs.getString("locatedFrom") + " and arrested by " + rs.getString("arrestedBy") + ". Suspect is currently under " + rs.getString("currentlyUnder") +".";
            }
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idTxt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        custom1 = new javax.swing.JCheckBox();
        matters1 = new javax.swing.JLabel();
        matters2 = new javax.swing.JLabel();
        mattersToBeInvestigatedTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ageTxt = new javax.swing.JLabel();
        victimImageLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        profTxt = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        crimeTypeTxt = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        facts = new javax.swing.JLabel();
        custom2 = new javax.swing.JCheckBox();
        factsOfTheCaseTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        custom3 = new javax.swing.JCheckBox();
        findings = new javax.swing.JLabel();
        investigationFindingsTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        signature = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        submitPanel = new javax.swing.JPanel();
        submitText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf_icon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 13, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Investigation Report on ID ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("People's Republic Of Bangladesh");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Ministry Of Home Affairs");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Bangladesh Police");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 20));

        idTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idTxt.setText("idTxt");
        jPanel1.add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("Matters to be Investigated");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        custom1.setBackground(new java.awt.Color(255, 255, 255));
        custom1.setText("Custom");
        custom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom1ActionPerformed(evt);
            }
        });
        jPanel1.add(custom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        matters1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        matters1.setText("matters1");
        jPanel1.add(matters1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        matters2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        matters2.setText("matters2");
        jPanel1.add(matters2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        mattersToBeInvestigatedTxt.setBackground(new Color(0,0,0,0));
        mattersToBeInvestigatedTxt.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        mattersToBeInvestigatedTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(mattersToBeInvestigatedTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 660, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("Information on Victim");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        nameTxt.setText("nameTxt");
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Age");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        ageTxt.setText("ageTxt");
        jPanel1.add(ageTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        victimImageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(victimImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 200, 200));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Profession");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        profTxt.setText("profTxt");
        jPanel1.add(profTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Victim Of");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        crimeTypeTxt.setText("crimeTypeTxt");
        jPanel1.add(crimeTypeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel12.setText("Facts of the Case");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        facts.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        facts.setText("facts");
        jPanel1.add(facts, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        custom2.setBackground(new java.awt.Color(255, 255, 255));
        custom2.setText("Custom");
        custom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom2ActionPerformed(evt);
            }
        });
        jPanel1.add(custom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        factsOfTheCaseTxt.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        factsOfTheCaseTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(factsOfTheCaseTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 660, 50));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel13.setText("Investigation Findings");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        custom3.setBackground(new java.awt.Color(255, 255, 255));
        custom3.setText("Custom");
        custom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom3ActionPerformed(evt);
            }
        });
        jPanel1.add(custom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, -1, -1));

        findings.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        findings.setText("Findings");
        jPanel1.add(findings, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, -1, 20));

        investigationFindingsTxt.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        investigationFindingsTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(investigationFindingsTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 640, 110));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel14.setText("Conclusion");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 730, -1, -1));

        jLabel15.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel15.setText("With all of the findings mentioned above, we hereby close the investigation.");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 760, -1, -1));

        signature.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signature.setText("    I.G.P Benazir Ahmed");
        signature.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        signature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signatureActionPerformed(evt);
            }
        });
        jPanel1.add(signature, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 840, 150, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel16.setText("Chief, Bangladesh Police");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 860, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 730, 930));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 1000, -1, -1));

        submitPanel.setBackground(new java.awt.Color(153, 204, 255));
        submitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitPanelMouseClicked(evt);
            }
        });
        submitPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitText.setText("Submit");
        submitPanel.add(submitText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 50, 10));

        jPanel2.add(submitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 960, 150, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 1000));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void custom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom1ActionPerformed
        if(custom1.isSelected()){
            mattersToBeInvestigatedTxt.setVisible(true);
            matters1.setVisible(false);
            matters2.setVisible(false);
        }
        else{
            mattersToBeInvestigatedTxt.setVisible(false);
            matters1.setVisible(true);
            matters2.setVisible(true);
             
            matters1.setText(txt1);
            matters2.setText(txt2);
        }
    }//GEN-LAST:event_custom1ActionPerformed

    private void custom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom2ActionPerformed
       if(custom2.isSelected()){
           factsOfTheCaseTxt.setVisible(true);
           facts.setVisible(false);
           factsOfTheCaseTxt.setText(defaultFactsText);
       }
       else{
          factsOfTheCaseTxt.setText("");
          factsOfTheCaseTxt.setVisible(false);
          facts.setVisible(true);
          facts.setText(txt3);
       }
    }//GEN-LAST:event_custom2ActionPerformed

    private void custom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom3ActionPerformed
        if(custom3.isSelected()){
            investigationFindingsTxt.setVisible(true);
            findings.setVisible(false);
            investigationFindingsTxt.setText(defaultInvestigationText);
        }
        else{
            findings.setVisible(true);
            findings.setText(txt4);
            investigationFindingsTxt.setText("");
            investigationFindingsTxt.setVisible(false);
        }
    }//GEN-LAST:event_custom3ActionPerformed

    private void signatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signatureActionPerformed

    private void submitPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitPanelMouseClicked
        submitText.setForeground(new java.awt.Color(255,255,255));
        
        if(mattersToBeInvestigatedTxt.getText().length()!=0 && factsOfTheCaseTxt.getText().length()!=0 && investigationFindingsTxt.getText().length()!=0 &&  mattersToBeInvestigatedTxt.isVisible() && factsOfTheCaseTxt.isVisible() && investigationFindingsTxt.isVisible()){
            mattersToBeInvestigated=mattersToBeInvestigatedTxt.getText();
            factsOfTheCase=factsOfTheCaseTxt.getText();
            invesitgationFindings=investigationFindingsTxt.getText();
           
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/crime record", "root", "");
                PreparedStatement pst = con.prepareStatement("insert into investigationreport values(?,?,?,?,?,?,?,?,?)");

                pst.setInt(1, id);
                pst.setString(2, name);
                pst.setString(3, age);
                pst.setString(4, profession);
                pst.setString(5, type);
                pst.setString(6, imageLocation);
                pst.setString(7, mattersToBeInvestigated);
                pst.setString(8, factsOfTheCase);
                pst.setString(9,invesitgationFindings);
                pst.executeUpdate();
            } catch (Exception e) {
            }
        
            String str="y";
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/crime record", "root", "");
                Statement s = con.createStatement();

                s.executeUpdate("update investigation set reportCreated='"+str+"' where id ='"+id+"' ");
                JOptionPane.showMessageDialog(null, "Investigation report on case id " + id + " has been created successfully");
            } catch (Exception e) {
            }
        }   
        else
            JOptionPane.showMessageDialog(null, "Invalid Info Provided");  
       
    }//GEN-LAST:event_submitPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createInvesitgationReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createInvesitgationReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createInvesitgationReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createInvesitgationReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createInvesitgationReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageTxt;
    private javax.swing.JLabel crimeTypeTxt;
    private javax.swing.JCheckBox custom1;
    private javax.swing.JCheckBox custom2;
    private javax.swing.JCheckBox custom3;
    private javax.swing.JLabel facts;
    private javax.swing.JTextField factsOfTheCaseTxt;
    private javax.swing.JLabel findings;
    private javax.swing.JLabel idTxt;
    private javax.swing.JTextField investigationFindingsTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel matters1;
    private javax.swing.JLabel matters2;
    private javax.swing.JTextField mattersToBeInvestigatedTxt;
    private javax.swing.JLabel nameTxt;
    private javax.swing.JLabel profTxt;
    private javax.swing.JTextField signature;
    private javax.swing.JPanel submitPanel;
    private javax.swing.JLabel submitText;
    private javax.swing.JLabel victimImageLabel;
    // End of variables declaration//GEN-END:variables
}
