/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.FocusEvent;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author HP
 */
public class Login1 extends javax.swing.JFrame {

    /**
     * Creates new form Login1
     */
    String hehe ="<HTML><u>Don't have an account?</u></HTML>";
    public Login1() {
        initComponents();
        this.setTitle("User Login");
        Image icon = new ImageIcon(this.getClass().getResource("/project_icon.png")).getImage();
        this.setIconImage(icon);
        
        HEHE.setText(hehe);
        invisibleEye.setVisible(false);
        addPlaceHolder(idTxt);
        addPlaceHolder(passwordTxt);
    }
    Connection con ;
    PreparedStatement pst;
    ResultSet rs;

    @Override
    public boolean contains(Point p) {
        return super.contains(p); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton1 = new com.k33ptoo.components.KButton();
        idTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        visibleEye = new javax.swing.JLabel();
        invisibleEye = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HEHE = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 41, -1));

        kGradientPanel1.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(215, 73, 253));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton2.setForeground(new java.awt.Color(0, 0, 0));
        kButton2.setText("Cancel");
        kButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kButton2.setkBackGroundColor(new java.awt.Color(204, 204, 255));
        kButton2.setkEndColor(new java.awt.Color(153, 102, 255));
        kButton2.setkFillButton(false);
        kButton2.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        kButton2.setkHoverForeGround(new java.awt.Color(0, 51, 51));
        kButton2.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton2.setkPressedColor(new java.awt.Color(204, 204, 255));
        kButton2.setkSelectedColor(new java.awt.Color(204, 255, 255));
        kButton2.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 120, 30));

        kButton1.setForeground(new java.awt.Color(0, 0, 0));
        kButton1.setText("Login");
        kButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(204, 204, 255));
        kButton1.setkEndColor(new java.awt.Color(153, 51, 255));
        kButton1.setkFillButton(false);
        kButton1.setkHoverEndColor(new java.awt.Color(102, 102, 102));
        kButton1.setkHoverForeGround(new java.awt.Color(0, 51, 51));
        kButton1.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        kButton1.setkPressedColor(new java.awt.Color(204, 204, 255));
        kButton1.setkSelectedColor(new java.awt.Color(204, 255, 255));
        kButton1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 110, 30));

        idTxt.setBackground(new Color(0,0,0,0));
        idTxt.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        idTxt.setForeground(new java.awt.Color(204, 204, 204));
        idTxt.setText("Enter User ID");
        idTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        idTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idTxtFocusLost(evt);
            }
        });
        idTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTxtKeyPressed(evt);
            }
        });
        kGradientPanel1.add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 217, 27));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User ID");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        passwordTxt.setBackground(new Color(0,0,0,0)
        );
        passwordTxt.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(204, 204, 204));
        passwordTxt.setText("Enter Password");
        passwordTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        passwordTxt.setEchoChar('\u0000');
        passwordTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTxtFocusLost(evt);
            }
        });
        passwordTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTxtKeyPressed(evt);
            }
        });
        kGradientPanel1.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 217, 29));

        visibleEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visibleEye.png"))); // NOI18N
        visibleEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visibleEyeMousePressed(evt);
            }
        });
        kGradientPanel1.add(visibleEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 20, 20));

        invisibleEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invisibleEye.png"))); // NOI18N
        invisibleEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                invisibleEyeMousePressed(evt);
            }
        });
        kGradientPanel1.add(invisibleEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 20, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome USER");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf_icon.png"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        HEHE.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        HEHE.setForeground(new java.awt.Color(255, 255, 255));
        HEHE.setText("Don't have an account?");
        HEHE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HEHEMouseClicked(evt);
            }
        });
        kGradientPanel1.add(HEHE, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 160, 20));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void addPlaceHolder(JTextField textField){
        Font f = idTxt.getFont();
        f = f.deriveFont(Font.ITALIC);
        textField.setFont(f);
        textField.setForeground(new Color(204,204,204));
    }
    
    public void removePlaceHolder(JTextField textField){
        Font f = idTxt.getFont();
        f = f.deriveFont(Font.PLAIN);
        textField.setFont(f);
        textField.setForeground(Color.BLACK);
    }
    
    ActionEvent kButton1ActionEvent;FocusEvent idTxtFocusEvent;FocusEvent passwordTxtFocusEvent;
    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        
        if(idTxt.getText().length()==0 || passwordTxt.getText().length()==0){
            JOptionPane.showMessageDialog(this, "NID or Password is Blank.");
        }
        else{
            try {
                String id = idTxt.getText();
                String password = passwordTxt.getText();
          
                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/crime record", "root", "");
                pst = con.prepareStatement("select * from user where id = ? and password=? ");
                pst.setString(1, id);
                pst.setString(2, password);
                rs = pst.executeQuery();

                if(rs.next()){
                    UserWindow.userid=Integer.parseInt(id);
         
                    UserWindow uw = new UserWindow();
                    this.hide();
                    uw.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this, "NID or Password did not match.\nTry again.");
                    idTxtFocusLost(idTxtFocusEvent);
                    passwordTxtFocusLost(passwordTxtFocusEvent);
                }

            }
            catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        new home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kButton2ActionPerformed

    private void visibleEyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visibleEyeMousePressed
        // TODO add your handling code here:
        visibleEye.setVisible(false);
        invisibleEye.setVisible(true);

        passwordTxt.setEchoChar((char)0);
    }//GEN-LAST:event_visibleEyeMousePressed

    private void invisibleEyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invisibleEyeMousePressed
        // TODO add your handling code here:
        invisibleEye.setVisible(false);
        visibleEye.setVisible(true);

        passwordTxt.setEchoChar(('*'));
    }//GEN-LAST:event_invisibleEyeMousePressed

    private void passwordTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        kButton1ActionPerformed(kButton1ActionEvent);
    }//GEN-LAST:event_passwordTxtKeyPressed

    private void passwordTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusLost
        if(passwordTxt.getText().equals("")){
            addPlaceHolder(passwordTxt);
            passwordTxt.setText("Enter Password");
            passwordTxt.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_passwordTxtFocusLost

    private void passwordTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusGained

        if(passwordTxt.getText().equals("Enter Password")){
            passwordTxt.setText("");
            passwordTxt.setEchoChar('*');
            removePlaceHolder(passwordTxt);
        }
    }//GEN-LAST:event_passwordTxtFocusGained

    private void idTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTxtKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        passwordTxt.requestFocus();
    }//GEN-LAST:event_idTxtKeyPressed

    private void idTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTxtFocusLost
        if(idTxt.getText().equals("")){
            addPlaceHolder(idTxt);
            idTxt.setText("Enter User ID");
        }
    }//GEN-LAST:event_idTxtFocusLost

    private void idTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTxtFocusGained

        if(idTxt.getText().equals("Enter User ID")){
            idTxt.setText("");
            removePlaceHolder(idTxt);
        }
    }//GEN-LAST:event_idTxtFocusGained

    private void HEHEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HEHEMouseClicked
        this.hide();
        new newUser().setVisible(true); 
    }//GEN-LAST:event_HEHEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HEHE;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel invisibleEye;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel visibleEye;
    // End of variables declaration//GEN-END:variables
}
