import  Package.ConnectionProvider;
import java.awt.Color;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */

    
    public login() {
        initComponents();
        
        invisibleEye.setVisible(false);
        
        //changing button colors
        this.setTitle("Login Window");
        newUserButton.setBackground(Color.BLACK);
        loginButton.setBackground(Color.BLACK);
        cancelButton.setBackground(Color.BLACK);  
        Image icon = new ImageIcon(this.getClass().getResource("/project_icon.png")).getImage();
        this.setIconImage(icon);
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IDText = new javax.swing.JTextField();
        PasswordText = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        newUserButton = new javax.swing.JButton();
        invisibleEye = new javax.swing.JLabel();
        visibleEye = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 50, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        IDText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextActionPerformed(evt);
            }
        });
        getContentPane().add(IDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 190, -1));

        PasswordText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PasswordText.setOpaque(false);
        PasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 190, -1));

        loginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        loginButton.setText("login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 110, 30));

        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_icon.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 120, 30));

        newUserButton.setForeground(new java.awt.Color(255, 255, 255));
        newUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N
        newUserButton.setText("New User");
        newUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 317, 120, -1));

        invisibleEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invisibleEye.png"))); // NOI18N
        invisibleEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                invisibleEyeMousePressed(evt);
            }
        });
        getContentPane().add(invisibleEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 20, 30));

        visibleEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visibleEye.png"))); // NOI18N
        visibleEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visibleEyeMousePressed(evt);
            }
        });
        getContentPane().add(visibleEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        setSize(new java.awt.Dimension(649, 418));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserButtonActionPerformed
        // TODO add your handling code here:
        newUser nu = new newUser();
        this.hide();
        nu.setVisible(true);
    }//GEN-LAST:event_newUserButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        if(IDText.getText().length()!=0 || PasswordText.getText().length()!=0){
            IDText.setText("");
            PasswordText.setText("");
        }
        else{
            this.hide();
            home h = new home();
            h.setVisible(true);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void invisibleEyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invisibleEyeMousePressed
        invisibleEye.setVisible(false);
        visibleEye.setVisible(true);

        PasswordText.setEchoChar('*');
    }//GEN-LAST:event_invisibleEyeMousePressed

    private void PasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextActionPerformed

    private void IDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if(IDText.getText().length()==0 || PasswordText.getText().length()==0){
            JOptionPane.showMessageDialog(this, "NID or Password is Blank.");
        }
        else{
            try {
                String id = IDText.getText();
                String password = PasswordText.getText();
          
                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/crime record", "root", "");
                pst = con.prepareStatement("select * from user where id = ? and password=? ");
                pst.setString(1, id);
                pst.setString(2, password);
                rs = pst.executeQuery();

                if(rs.next()){
                    UserWindow.userid=Integer.parseInt(id);
         
                    UserWindow uw = new UserWindow();
                    this.hide();
                    uw.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this, "NID or Password did not match.\nTry again.");
                    IDText.setText("");
                    PasswordText.setText("");
                    IDText.requestFocus();
                }

            }
            catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void visibleEyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visibleEyeMousePressed
        // TODO add your handling code here:
        visibleEye.setVisible(false);
        invisibleEye.setVisible(true);

        PasswordText.setEchoChar((char)0);
    }//GEN-LAST:event_visibleEyeMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDText;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel invisibleEye;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton newUserButton;
    private javax.swing.JLabel visibleEye;
    // End of variables declaration//GEN-END:variables
}
