import com.mysql.cj.protocol.Resultset;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
public class PRACTICE2 extends javax.swing.JFrame {

    /**
     * Creates new form PRACTICE2
     */
    public PRACTICE2() {
        initComponents();
        this.setTitle("Admin Login");
        Image icon = new ImageIcon(this.getClass().getResource("/project_icon.png")).getImage();
        this.setIconImage(icon);
        invisibleEye.setVisible(false);
        addPlaceHolder(idTxt);
        addPlaceHolder(passwordTxt);
    }
    Connection con ;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        idTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        kButton1 = new com.k33ptoo.components.KButton();
        invisibleEye = new javax.swing.JLabel();
        visibleEye = new javax.swing.JLabel();
        kButton2 = new com.k33ptoo.components.KButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idTxt.setBackground(new Color(0,0,0,0));
        idTxt.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        idTxt.setForeground(new java.awt.Color(204, 204, 204));
        idTxt.setText("Enter ID");
        idTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(143, 255, 249)));
        idTxt.setOpaque(false);
        idTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idTxtFocusLost(evt);
            }
        });
        idTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTxtKeyPressed(evt);
            }
        });
        kGradientPanel1.add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 207, 160, 29));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("ID");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 184, 39, -1));

        passwordTxt.setBackground(new Color(0,0,0,0)
        );
        passwordTxt.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(204, 204, 204));
        passwordTxt.setText("Enter Password");
        passwordTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(146, 247, 235)));
        passwordTxt.setEchoChar('\u0000');
        passwordTxt.setOpaque(false);
        passwordTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTxtFocusLost(evt);
            }
        });
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        passwordTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTxtKeyPressed(evt);
            }
        });
        kGradientPanel1.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 277, 160, 27));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Password");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 254, -1, -1));

        kButton1.setText("Login");
        kButton1.setkBackGroundColor(new java.awt.Color(146, 247, 235));
        kButton1.setkBorderRadius(20);
        kButton1.setkEndColor(new java.awt.Color(146, 247, 235));
        kButton1.setkFillButton(false);
        kButton1.setkForeGround(new java.awt.Color(204, 255, 255));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton1.setkPressedColor(new java.awt.Color(153, 153, 255));
        kButton1.setkSelectedColor(new java.awt.Color(153, 153, 255));
        kButton1.setkStartColor(new java.awt.Color(204, 255, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 110, 30));

        invisibleEye.setForeground(new java.awt.Color(255, 255, 255));
        invisibleEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invisibleEye.png"))); // NOI18N
        invisibleEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                invisibleEyeMousePressed(evt);
            }
        });
        kGradientPanel1.add(invisibleEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        visibleEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visibleEye.png"))); // NOI18N
        visibleEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visibleEyeMousePressed(evt);
            }
        });
        kGradientPanel1.add(visibleEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        kButton2.setText("Cancel");
        kButton2.setkBorderRadius(20);
        kButton2.setkEndColor(new java.awt.Color(146, 247, 235));
        kButton2.setkFillButton(false);
        kButton2.setkForeGround(new java.awt.Color(204, 255, 255));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton2.setkPressedColor(new java.awt.Color(153, 153, 255));
        kButton2.setkSelectedColor(new java.awt.Color(153, 153, 255));
        kButton2.setkStartColor(new java.awt.Color(204, 255, 255));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 110, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Neon.jpeg"))); // NOI18N
        jLabel5.setOpaque(true);
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 140));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void addPlaceHolder(JTextField textField){
        Font f = idTxt.getFont();
        f = f.deriveFont(Font.ITALIC);
        textField.setFont(f);
        textField.setForeground(new Color(204,204,204));
    }
    
    public void removePlaceHolder(JTextField textField){
        Font f = idTxt.getFont();
        f = f.deriveFont(Font.PLAIN);
        textField.setFont(f);
        textField.setForeground(Color.WHITE);
    }
    
    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void idTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTxtFocusGained
        if(idTxt.getText().equals("Enter ID")){
           idTxt.setText("");
           removePlaceHolder(idTxt);
       }
    }//GEN-LAST:event_idTxtFocusGained

    private void idTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTxtFocusLost
       if(idTxt.getText().equals("")){
           addPlaceHolder(idTxt);
           idTxt.setText("Enter ID");
       }
    }//GEN-LAST:event_idTxtFocusLost

    private void passwordTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusGained
       if(passwordTxt.getText().equals("Enter Password")){
          passwordTxt.setText("");
          passwordTxt.setEchoChar('*');
          removePlaceHolder(passwordTxt);
       }
    }//GEN-LAST:event_passwordTxtFocusGained

    private void passwordTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusLost
       if(passwordTxt.getText().equals("")){
           addPlaceHolder(passwordTxt);
          passwordTxt.setText("Enter Password");
          passwordTxt.setEchoChar('\u0000');
       }
    }//GEN-LAST:event_passwordTxtFocusLost

    private void idTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTxtKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER)
           passwordTxt.requestFocus();
    }//GEN-LAST:event_idTxtKeyPressed
    ActionEvent kButtonActionEvent;
    private void passwordTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER)
           kButton1ActionPerformed(kButtonActionEvent);
    }//GEN-LAST:event_passwordTxtKeyPressed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
       if(idTxt.getText().length()==0 || passwordTxt.getText().length()==0){
           JOptionPane.showMessageDialog(this, "ID or Password is Blank.");
       }
        else{
             try {
                String id = idTxt.getText();
                String password = passwordTxt.getText();


                Class.forName("com.mysql.cj.jdbc.Driver");
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/crime record", "root", "");
                pst = con.prepareStatement("select * from admin where id = ? and password=? ");
                pst.setString(1, id);
                pst.setString(2, password);
                rs = pst.executeQuery();
            
                if(rs.next()){
                    AdminWindow aw = new AdminWindow();
                    this.dispose();
                    aw.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this, "ID or Password did not match.\nTry again.");
                    idTxt.setText("");
                    passwordTxt.setText("");
                    idTxt.requestFocus();
                }
            
       } catch (ClassNotFoundException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
    }//GEN-LAST:event_kButton1ActionPerformed

    private void invisibleEyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invisibleEyeMousePressed
        invisibleEye.setVisible(false);
        visibleEye.setVisible(true);

        passwordTxt.setEchoChar(('*'));
    }//GEN-LAST:event_invisibleEyeMousePressed

    private void visibleEyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visibleEyeMousePressed
         visibleEye.setVisible(false);
        invisibleEye.setVisible(true);

        passwordTxt.setEchoChar((char)0);
    }//GEN-LAST:event_visibleEyeMousePressed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
      new home().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_kButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRACTICE2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRACTICE2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRACTICE2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRACTICE2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRACTICE2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel invisibleEye;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel visibleEye;
    // End of variables declaration//GEN-END:variables
}
