import java.util.Random;
import java.awt.Color;
import java.awt.Image;
import java.awt.Label;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */

public class reportingCrime extends javax.swing.JFrame {

    /**
     * Creates new form reportingCrime
     */
    String victimImageLocation="",suspectImageLocation="";
    public reportingCrime() {
        initComponents(); 
      
        witText.setVisible(false);
        witnessLabel.setVisible(false);
        statOfWitLabel.setVisible(false);
        statOfWitText.setVisible(false);
        submitButton.setBackground(Color.white);
        
        submitButton.setBackground(Color.WHITE);
        jButton1.setBackground(Color.WHITE);
        jButton2.setBackground(Color.WHITE);
        
        this.setTitle("Reporting Crime");
        Image icon = new ImageIcon(this.getClass().getResource("/project_icon.png")).getImage();
        this.setIconImage(icon);
        
        this.setBackground(Color.CYAN);
    }
    Random r = new Random();
    int reportId = 2019331000;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        suspectName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        suspectDetails = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        suspectImgLabel = new javax.swing.JLabel();
        suspectImgText = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        suspectAge = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        typeOfCrime = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        witnessLabel = new javax.swing.JLabel();
        statOfWitLabel = new javax.swing.JLabel();
        witText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        checkbox = new javax.swing.JCheckBox();
        crimePlace_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        statOfWitText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        reportFiledOnDate = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        dateHappenedDate = new com.toedter.calendar.JDateChooser();
        submitButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        prof_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        blood = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        victimAge = new javax.swing.JTextField();
        victimImgText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        victimImgLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        victimName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+ve", "A-ve", "B+ve", "B-ve", "AB+ve", "AB-ve", "O+ve", "O-ve" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Suspect Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 105, -1));

        suspectName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        suspectName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suspectNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suspectNameMouseExited(evt);
            }
        });
        suspectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspectNameActionPerformed(evt);
            }
        });
        jPanel1.add(suspectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 250, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Suspect Details");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, -1));

        suspectDetails.setColumns(20);
        suspectDetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        suspectDetails.setRows(5);
        suspectDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suspectDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suspectDetailsMouseExited(evt);
            }
        });
        jScrollPane4.setViewportView(suspectDetails);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 250, 110));

        jLabel13.setBackground(new java.awt.Color(204, 255, 255));
        jLabel13.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel13.setText("Possible Suspect");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        suspectImgLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        jPanel1.add(suspectImgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 200, 200));

        suspectImgText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        suspectImgText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suspectImgTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suspectImgTextMouseExited(evt);
            }
        });
        suspectImgText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspectImgTextActionPerformed(evt);
            }
        });
        jPanel1.add(suspectImgText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 200, -1));

        jButton2.setText("Attach");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Image");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Suspect Age");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        suspectAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        suspectAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suspectAgeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suspectAgeMouseExited(evt);
            }
        });
        suspectAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspectAgeActionPerformed(evt);
            }
        });
        jPanel1.add(suspectAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 250, -1));

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, 400, 600));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typeOfCrime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        typeOfCrime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theft", "Kidnap", "Stealing", "Robbery", "Murder", "Rape", "Cyber Crime", "Sexual Abuse", "Missing Person", "Others" }));
        typeOfCrime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                typeOfCrimeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                typeOfCrimeMouseExited(evt);
            }
        });
        typeOfCrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeOfCrimeActionPerformed(evt);
            }
        });
        jPanel2.add(typeOfCrime, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 240, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Type of Crime");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Description");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        witnessLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        witnessLabel.setText("Witness Name");
        jPanel2.add(witnessLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        statOfWitLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        statOfWitLabel.setText("Witness Statement");
        jPanel2.add(statOfWitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        witText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        witText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                witTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                witTextMouseExited(evt);
            }
        });
        jPanel2.add(witText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 240, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Witness Present");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        checkbox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkbox.setText("Yes");
        checkbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkboxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkboxMouseExited(evt);
            }
        });
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        jPanel2.add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 50, 20));

        crimePlace_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        crimePlace_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crimePlace_txtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crimePlace_txtMouseExited(evt);
            }
        });
        crimePlace_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crimePlace_txtActionPerformed(evt);
            }
        });
        jPanel2.add(crimePlace_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 240, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("PLace of Crime");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        descriptionText.setColumns(20);
        descriptionText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        descriptionText.setRows(5);
        descriptionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                descriptionTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                descriptionTextMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(descriptionText);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 240, 103));

        jLabel7.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel7.setText("Crime Details");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        statOfWitText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statOfWitText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        statOfWitText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statOfWitTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statOfWitTextMouseExited(evt);
            }
        });
        jPanel2.add(statOfWitText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 240, 100));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Date Happaned");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        reportFiledOnDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportFiledOnDateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportFiledOnDateMouseExited(evt);
            }
        });
        jPanel2.add(reportFiledOnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 240, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Report Filed On");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        dateHappenedDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dateHappenedDateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dateHappenedDateMouseExited(evt);
            }
        });
        jPanel2.add(dateHappenedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 240, -1));

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 430, 600));

        submitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel6.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 710, 120, 30));

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prof_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        prof_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prof_txtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prof_txtMouseExited(evt);
            }
        });
        jPanel5.add(prof_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 200, 30));

        address_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        address_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                address_txtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                address_txtMouseExited(evt);
            }
        });
        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtActionPerformed(evt);
            }
        });
        jPanel5.add(address_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 200, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Address");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Profession");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 40));

        blood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+ve", "A-ve", "B+ve", "B-ve", "AB+ve", "AB-ve", "O+ve", "O-ve" }));
        blood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bloodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bloodMouseExited(evt);
            }
        });
        blood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodActionPerformed(evt);
            }
        });
        jPanel5.add(blood, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 200, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Blood Group");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 40));

        jLabel3.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel3.setText("Personal Information");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 50));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Age");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 40));

        victimAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        victimAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                victimAgeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                victimAgeMouseExited(evt);
            }
        });
        victimAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                victimAgeActionPerformed(evt);
            }
        });
        jPanel5.add(victimAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 200, 30));

        victimImgText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        victimImgText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                victimImgTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                victimImgTextMouseExited(evt);
            }
        });
        jPanel5.add(victimImgText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 200, 30));

        jButton1.setText("Attach");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 80, -1));

        victimImgLabel.setForeground(new java.awt.Color(102, 102, 102));
        victimImgLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        jPanel5.add(victimImgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 200, 200));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Image");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 40));

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 380, 600));

        victimName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        victimName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                victimNameMouseEntered(evt);
            }
        });
        victimName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                victimNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                victimNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                victimNameKeyTyped(evt);
            }
        });
        jPanel6.add(victimName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 190, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("Victim Name");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 760));

        setSize(new java.awt.Dimension(1316, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:     
        try {
            String url = "jdbc:mysql://localhost/crime record";
            String username = "root";
            String pass = "";
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(url, username, pass);
            
            pst = con.prepareStatement("select id from report where id=? ");
            
            //the following code block is for preventing multiple reports from having same id
            int id = this.reportId+r.nextInt(100);
            pst.setInt(1, id);
            rs = pst.executeQuery();
            int notPresent=0;
            while(notPresent==0){
                if(rs.next()==false){
                    notPresent=1;
                }
                else{
                    id =this.reportId+r.nextInt(100);
                    pst.setInt(1, id);
                    rs = pst.executeQuery();
                }
            }
            
                
            
            String victim = victimName.getText();
            String crimeType = typeOfCrime.getSelectedItem().toString();
            String description = descriptionText.getText();
            String suspect = suspectName.getText();
            String details_on_suspect = suspectDetails.getText();
            String bloodGrp = blood.getSelectedItem().toString();
            String prof = prof_txt.getText();
            String address = address_txt.getText();
            String crimePlace = crimePlace_txt.getText();
            String witness = witText.getText();
            String witnessStat = statOfWitText.getText();
            String witnessPresent;
            if(checkbox.isSelected())
                witnessPresent="y";
            else
                witnessPresent="n";
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            String dateHappened = sdf.format(dateHappenedDate.getDate());
            String reportFiledOn=sdf.format(reportFiledOnDate.getDate());
            
            String query = "insert into report values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
  
            pst = con.prepareStatement(query);
 
           
            pst.setInt(1, id);
            pst.setString(2, victim);
            pst.setString(3, crimeType);
            pst.setString(4, description);
            pst.setString(5, suspect);
            pst.setString(6, details_on_suspect);
            pst.setString(7, bloodGrp);
            pst.setString(8, prof);
            pst.setString(9, address);
            pst.setString(10,crimePlace);
            pst.setString(11,witnessPresent );
            pst.setString(12,witness);
            pst.setString(13,witnessStat);
            pst.setInt(14, UserWindow.userid);
            pst.setString(15, victimAge.getText());
            pst.setString(16, suspectAge.getText());
            pst.setString(17, dateHappened);
            pst.setString(18, reportFiledOn);
            pst.setString(19, victimImageLocation);
            pst.setString(20, suspectImageLocation);
            
            pst.executeUpdate();
            
           
                
            JOptionPane.showMessageDialog(null, "Report Successfully Submitted\nYour report ID is " + id +".\nRemember this for further use.");
            
            victimName.setText("");
            typeOfCrime.setSelectedIndex(0);
            descriptionText.setText("");
            suspectName.setText("");
            suspectDetails.setText("");
            
            blood.setSelectedIndex(0);
            prof_txt.setText("");
            address_txt.setText("");
            crimePlace_txt.setText("");
          
            witText.setText("");
            statOfWitText.setText("");
            victimAge.setText("");
            suspectAge.setText("");
            suspectImgLabel.setIcon(null);
            victimImgLabel.setIcon(null);
            suspectImgText.setText("");
            victimImgText.setText("");
            
            //now there is one more thing while reporting a crime
            //it will be good for us if we update the progress table and investigation Table while reporting a crime
            
           query = "insert into progress values (?,?,?,?,?,?,?,?,?,?)";
           pst = con.prepareStatement(query);
           
           String investigationStarted="n";
           String createFIR = "n";
           String evidenceCollected ="n";
           String suspectLocated="n";
           String victimFound="n";
           String suspectConfessed ="n";
           String consentRequested ="n";
           String consentGiven = "n";
           
           pst.setInt(1, id);
           pst.setString(2, investigationStarted);
           pst.setString(3, createFIR);
           pst.setString(4, evidenceCollected);
           pst.setString(5, suspectLocated);
           pst.setString(6, victimFound);
           pst.setString(7, suspectConfessed);
           pst.setInt(8, UserWindow.userid);
           pst.setString(9, consentRequested);
           pst.setString(10, consentGiven);
           pst.executeUpdate();
           
           query = "insert into investigation values (?,?,?,?,?,?,?,?,?,?,?,?)";
           pst = con.prepareStatement(query);
           
           pst.setInt(1, id);
           pst.setString(2, "n");
           pst.setString(3, "N/A");
           pst.setString(4, "N/A");
           pst.setString(5, "N/A");
           pst.setString(6, "N/A");
           pst.setString(7, "N/A");
           pst.setString(8, "N/A");
           pst.setString(9, "N/A");
           pst.setString(10, "N/A");
           pst.setString(11, "N/A");
           pst.setString(12, "N/A");
           pst.executeUpdate();
            
        }  catch (ClassNotFoundException ex) {
            Logger.getLogger(reportingCrime.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(reportingCrime.class.getName()).log(Level.SEVERE, null, ex);
        } 
       
    }//GEN-LAST:event_submitButtonActionPerformed

    private void suspectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suspectNameActionPerformed

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        // TODO add your handling code here:
        if(checkbox.isSelected()){
            witnessLabel.setVisible(true);
            witText.setVisible(true);
            statOfWitLabel.setVisible(true);
            statOfWitText.setVisible(true);
        }
        else{
            witnessLabel.setVisible(false);
            witText.setVisible(false);
            statOfWitLabel.setVisible(false);
            statOfWitText.setVisible(false);
        }
    }//GEN-LAST:event_checkboxActionPerformed

    private void address_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void bloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodActionPerformed

    private void crimePlace_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crimePlace_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crimePlace_txtActionPerformed

    private void typeOfCrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeOfCrimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeOfCrimeActionPerformed

    private void victimNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_victimNameKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_victimNameKeyTyped

    private void victimNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_victimNameKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_victimNameKeyPressed

    private void victimNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_victimNameKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_victimNameKeyReleased

    private void victimNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_victimNameMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_victimNameMouseEntered

    private void victimAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_victimAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_victimAgeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JFileChooser fc= new JFileChooser();
       fc.showOpenDialog(null);
       File f = fc.getSelectedFile();
       String fileLocation = f.getAbsolutePath();
       
       String fileName = f.getName();
       victimImgText.setText(fileName);
      
       victimImageLocation=f.getAbsolutePath();
       
       Image getAbsolutePath = null;
       ImageIcon icon = new ImageIcon(fileLocation);
       Image image = icon.getImage().getScaledInstance(victimImgLabel.getWidth(), victimImgLabel.getHeight(), Image.SCALE_SMOOTH);
       victimImgLabel.setIcon(icon);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void suspectImgTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspectImgTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suspectImgTextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       JFileChooser fc= new JFileChooser();
       fc.showOpenDialog(null);
       File f = fc.getSelectedFile();
       String fileLocation = f.getAbsolutePath();
       
       String fileName = f.getName();
       suspectImgText.setText(fileName);
       
       suspectImageLocation=f.getAbsolutePath();
       
       Image getAbsolutePath = null;
       ImageIcon icon = new ImageIcon(fileLocation);
       Image image = icon.getImage().getScaledInstance(suspectImgLabel.getWidth(), suspectImgLabel.getHeight(), Image.SCALE_SMOOTH);
       suspectImgLabel.setIcon(icon);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void suspectAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspectAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suspectAgeActionPerformed

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        jPanel2.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
         jPanel2.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
       jPanel5.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
       jPanel5.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        jPanel1.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
       jPanel1.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_jPanel1MouseExited

    private void suspectNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suspectNameMouseEntered
      jPanel1.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_suspectNameMouseEntered

    private void suspectNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suspectNameMouseExited
       jPanel1.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_suspectNameMouseExited

    private void suspectDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suspectDetailsMouseEntered
       jPanel1.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_suspectDetailsMouseEntered

    private void suspectDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suspectDetailsMouseExited
        jPanel1.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_suspectDetailsMouseExited

    private void suspectAgeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suspectAgeMouseEntered
         jPanel1.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_suspectAgeMouseEntered

    private void suspectAgeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suspectAgeMouseExited
        jPanel1.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_suspectAgeMouseExited

    private void suspectImgTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suspectImgTextMouseEntered
        jPanel1.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_suspectImgTextMouseEntered

    private void suspectImgTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suspectImgTextMouseExited
       jPanel1.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_suspectImgTextMouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
       jPanel1.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jPanel1.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_jButton2MouseExited

    private void typeOfCrimeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeOfCrimeMouseEntered
        jPanel2.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_typeOfCrimeMouseEntered

    private void typeOfCrimeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeOfCrimeMouseExited
       jPanel2.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_typeOfCrimeMouseExited

    private void descriptionTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionTextMouseEntered
      jPanel2.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_descriptionTextMouseEntered

    private void descriptionTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionTextMouseExited
        jPanel2.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_descriptionTextMouseExited

    private void crimePlace_txtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crimePlace_txtMouseEntered
      jPanel2.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_crimePlace_txtMouseEntered

    private void crimePlace_txtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crimePlace_txtMouseExited
        jPanel2.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_crimePlace_txtMouseExited

    private void dateHappenedDateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateHappenedDateMouseEntered
        jPanel2.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_dateHappenedDateMouseEntered

    private void dateHappenedDateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateHappenedDateMouseExited
       jPanel2.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_dateHappenedDateMouseExited

    private void reportFiledOnDateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportFiledOnDateMouseEntered
       jPanel2.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_reportFiledOnDateMouseEntered

    private void reportFiledOnDateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportFiledOnDateMouseExited
       jPanel2.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_reportFiledOnDateMouseExited

    private void checkboxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkboxMouseEntered
        jPanel2.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_checkboxMouseEntered

    private void checkboxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkboxMouseExited
        jPanel2.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_checkboxMouseExited

    private void witTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_witTextMouseEntered
      jPanel2.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_witTextMouseEntered

    private void witTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_witTextMouseExited
        jPanel2.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_witTextMouseExited

    private void prof_txtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prof_txtMouseEntered
        jPanel5.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_prof_txtMouseEntered

    private void prof_txtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prof_txtMouseExited
        jPanel5.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_prof_txtMouseExited

    private void address_txtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_address_txtMouseEntered
        jPanel5.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_address_txtMouseEntered

    private void address_txtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_address_txtMouseExited
       jPanel5.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_address_txtMouseExited

    private void bloodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloodMouseEntered
         jPanel5.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_bloodMouseEntered

    private void bloodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloodMouseExited
         jPanel5.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_bloodMouseExited

    private void victimAgeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_victimAgeMouseEntered
       jPanel5.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_victimAgeMouseEntered

    private void victimAgeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_victimAgeMouseExited
       jPanel5.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_victimAgeMouseExited

    private void victimImgTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_victimImgTextMouseEntered
       jPanel5.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_victimImgTextMouseEntered

    private void victimImgTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_victimImgTextMouseExited
        jPanel5.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_victimImgTextMouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
       jPanel5.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jPanel5.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_jButton1MouseExited

    private void statOfWitTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statOfWitTextMouseExited
        jPanel2.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_statOfWitTextMouseExited

    private void statOfWitTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statOfWitTextMouseEntered
        jPanel2.setBackground(new Color(102,204,255));
    }//GEN-LAST:event_statOfWitTextMouseEntered

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportingCrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportingCrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportingCrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportingCrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportingCrime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_txt;
    private javax.swing.JComboBox<String> blood;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JTextField crimePlace_txt;
    private com.toedter.calendar.JDateChooser dateHappenedDate;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField prof_txt;
    private com.toedter.calendar.JDateChooser reportFiledOnDate;
    private javax.swing.JLabel statOfWitLabel;
    private javax.swing.JTextField statOfWitText;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField suspectAge;
    private javax.swing.JTextArea suspectDetails;
    private javax.swing.JLabel suspectImgLabel;
    private javax.swing.JTextField suspectImgText;
    private javax.swing.JTextField suspectName;
    private javax.swing.JComboBox<String> typeOfCrime;
    private javax.swing.JTextField victimAge;
    private javax.swing.JLabel victimImgLabel;
    private javax.swing.JTextField victimImgText;
    private javax.swing.JTextField victimName;
    private javax.swing.JTextField witText;
    private javax.swing.JLabel witnessLabel;
    // End of variables declaration//GEN-END:variables
}
