import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import com.itextpdf.text.*;
import com.itextpdf.text.Image;

import java.awt.Color;
//import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.TimerTask;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class seeFIRcopy extends javax.swing.JFrame {

    /**
     * Creates new form seeFIRcopy
     */
    public static String id;
    public seeFIRcopy() {
        initComponents();
        
        showDoc(id);
        this.setTitle("FIR Copy");
        java.awt.Image icon = new ImageIcon(this.getClass().getResource("/project_icon.png")).getImage();
        this.setIconImage(icon);
    }
    public String FindingOutComplaintFilerNameFromUserTableInDB(int filerID){
        String x="";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/crime record", "root", "");
            PreparedStatement pst = con.prepareStatement("select * from user where id=? ");
            
            
            pst.setInt(1, filerID);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                    x=rs.getString("name");
                }
           
        } catch (Exception e) {
        }
        return x;
   }   
    public void showDoc(String s){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/crime record", "root", "");
            PreparedStatement pst = con.prepareStatement("select * from report where id=? ");
            
            int ID = Integer.parseInt(s);
            pst.setInt(1, ID);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                id_noTxt.setText(s);
                victimTxt.setText(rs.getString("victim"));
                crimeTypeTxt.setText(rs.getString("crimeType"));
                descriptionTxt.setText(rs.getString("description"));
                placeTxt.setText(rs.getString("crimePlace"));
                suspectTxt.setText(rs.getString("suspect"));
                suspectDetailsTxt.setText(rs.getString("suspectDetails"));
                witnessTxt.setText(rs.getString("witness"));
                witnessStatementTxt.setText(rs.getString("witnessStatement"));
                String filerName =FindingOutComplaintFilerNameFromUserTableInDB(UserWindow.userid);
                System.out.println(filerName);
                complaintFilerTxt.setText(filerName);
            }
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        app1 = new com.k33ptoo.App();
        app2 = new com.k33ptoo.App();
        componentMoverUtil1 = new com.k33ptoo.utils.ComponentMoverUtil();
        componentResizerUtil1 = new com.k33ptoo.utils.ComponentResizerUtil();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        pdfIconLabel = new javax.swing.JLabel();
        reportIDLabel = new javax.swing.JLabel();
        id_noTxt = new javax.swing.JLabel();
        victimNameLabel = new javax.swing.JLabel();
        victimTxt = new javax.swing.JLabel();
        crimeTypeLabel = new javax.swing.JLabel();
        crimeTypeTxt = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        descriptionTxt = new javax.swing.JLabel();
        crimePlaceLabel = new javax.swing.JLabel();
        placeTxt = new javax.swing.JLabel();
        suspectLabel = new javax.swing.JLabel();
        suspectTxt = new javax.swing.JLabel();
        suspectDetailsLabel = new javax.swing.JLabel();
        suspectDetailsTxt = new javax.swing.JLabel();
        witnessLabel = new javax.swing.JLabel();
        witnessTxt = new javax.swing.JLabel();
        witnessStatementLabel = new javax.swing.JLabel();
        witnessStatementTxt = new javax.swing.JLabel();
        consentedByLabel = new javax.swing.JLabel();
        filedByLabel = new javax.swing.JLabel();
        complaintFilerTxt = new javax.swing.JLabel();
        FIRfilerTxt = new javax.swing.JLabel();
        pdfButton = new javax.swing.JPanel();
        downloadReportLabel = new javax.swing.JLabel();
        ss = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        titleLabel.setText("First Information Report (FIR)");
        jPanel2.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        pdfIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf_icon.png"))); // NOI18N
        jPanel2.add(pdfIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        reportIDLabel.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        reportIDLabel.setText("Report ID :");
        jPanel2.add(reportIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        id_noTxt.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        id_noTxt.setText("id_no(should be made bold)");
        jPanel2.add(id_noTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        victimNameLabel.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        victimNameLabel.setText("Victim Name        :");
        jPanel2.add(victimNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        victimTxt.setText("victim Txt");
        jPanel2.add(victimTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        crimeTypeLabel.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        crimeTypeLabel.setText("Crime Type         :");
        jPanel2.add(crimeTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        crimeTypeTxt.setText("crimeTypeTxt");
        jPanel2.add(crimeTypeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        descriptionLabel.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        descriptionLabel.setText("Description        :");
        jPanel2.add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        descriptionTxt.setText("descriptonTxt");
        jPanel2.add(descriptionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        crimePlaceLabel.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        crimePlaceLabel.setText("Crime Place        :");
        jPanel2.add(crimePlaceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        placeTxt.setText("place");
        jPanel2.add(placeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        suspectLabel.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        suspectLabel.setText("Possible Suspect   :");
        jPanel2.add(suspectLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        suspectTxt.setText("suspectTxt");
        jPanel2.add(suspectTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        suspectDetailsLabel.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        suspectDetailsLabel.setText("Details on Suspect :");
        jPanel2.add(suspectDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        suspectDetailsTxt.setText("suspectDetails");
        jPanel2.add(suspectDetailsTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        witnessLabel.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        witnessLabel.setText("Witness            :");
        jPanel2.add(witnessLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, 20));

        witnessTxt.setText("wit");
        jPanel2.add(witnessTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        witnessStatementLabel.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        witnessStatementLabel.setText("Witness Statement  :");
        jPanel2.add(witnessStatementLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, 20));

        witnessStatementTxt.setText("witnessStat");
        jPanel2.add(witnessStatementTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        consentedByLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        consentedByLabel.setText("Consented By");
        jPanel2.add(consentedByLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 720, -1, -1));

        filedByLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        filedByLabel.setText("Filed By");
        jPanel2.add(filedByLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 720, -1, -1));

        complaintFilerTxt.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        complaintFilerTxt.setText("complaintFilerTxt");
        jPanel2.add(complaintFilerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 750, -1, -1));

        FIRfilerTxt.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        FIRfilerTxt.setText("S.I. Monjurul Haque");
        jPanel2.add(FIRfilerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 750, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 620, 830));

        pdfButton.setBackground(new java.awt.Color(0, 160, 238));
        pdfButton.setForeground(new java.awt.Color(153, 102, 255));
        pdfButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pdfButtonMouseClicked(evt);
            }
        });
        pdfButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        downloadReportLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        downloadReportLabel.setForeground(new java.awt.Color(255, 255, 255));
        downloadReportLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download.png"))); // NOI18N
        downloadReportLabel.setText("Download Report");
        downloadReportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downloadReportLabelMouseClicked(evt);
            }
        });
        pdfButton.add(downloadReportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(pdfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 890, 190, 50));

        ss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ss.png"))); // NOI18N
        ss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ssMouseClicked(evt);
            }
        });
        jPanel1.add(ss, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 890, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void downloadReportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downloadReportLabelMouseClicked
        // TODO add your handling code here:
        downloadReportLabel.setForeground(new java.awt.Color(255,255,255));
        
    }//GEN-LAST:event_downloadReportLabelMouseClicked
    public void DelayKeramoti(BufferedImage capture){
        Timer timer1 = new Timer();

        TimerTask task1 = new TimerTask() {
            @Override
            public void run() {
                jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));  
                jPanel1.setBackground(new Color(191,253,255));
                jPanel2.setBackground(new Color(255,255,255));
            }
        };
        timer1.schedule(task1, 1000);

        Timer timer2 = new Timer();
        TimerTask task2 = new TimerTask() {
            @Override
            public void run() {
              JOptionPane.showMessageDialog(null, "Screen Shot taken");
            }
        };
        timer2.schedule(task2, 1100);


        Timer timer3 = new Timer();
        TimerTask task3 = new TimerTask() {
            @Override
            public void run() {
                 JFileChooser fc = new JFileChooser();
                 fc.showSaveDialog(null);
                 fc.setDialogTitle("Select File Location");

                 File f = fc.getSelectedFile();

                 try {
                     ImageIO.write(capture, "png", new File(f.getPath()+".png"));
                 } catch (IOException ex) {
                      JOptionPane.showMessageDialog(null, "Please choose a valid location");
                 }
                 JOptionPane.showMessageDialog(null, "Screen Shot Saved at " + f.getParent());
             }     
        };
        timer3.schedule(task3, 2000);
 }
    private void ssMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssMouseClicked
        // TODO add your handling code here:
        try {
            Rectangle r = new Rectangle(jPanel1.getLocationOnScreen().x,jPanel1.getLocationOnScreen().y, 813,950);
            BufferedImage capture = new Robot().createScreenCapture(r);
            ImageIcon image = new ImageIcon(capture);
            
            //jLabel1.setIcon(image);
            
            jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 255)));
            DelayKeramoti(capture);
              
        } catch (Exception e) {
           
        }
    }//GEN-LAST:event_ssMouseClicked

    private void pdfButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdfButtonMouseClicked
        pdfButton.setBackground(new Color(204,255,255));
        downloadReportLabel.setForeground(new Color(0,0,0));
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/crime record", "root", "");
            PreparedStatement pst = con.prepareStatement("select * from report where id=? ");
            
            int ID = Integer.parseInt(id);
            pst.setInt(1, ID);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                try{
                    JFileChooser fc = new JFileChooser();
                    fc.showSaveDialog(this);
                    fc.setDialogTitle("Select File Location");
                    
                    File f = fc.getSelectedFile();

                    Document doc = new Document();
                    PdfWriter.getInstance(doc,new FileOutputStream(f.getAbsolutePath()+".pdf"));
                    JOptionPane.showMessageDialog(null, "PDF saved at "+f.getParent());
                    
                    doc.open();
                    
                     Font largeBold =new Font(Font.FontFamily.COURIER,18,Font.BOLD);
                     Font smallBold =new Font(Font.FontFamily.COURIER,13,Font.BOLD);
                     Font titleFont = new Font(Font.FontFamily.COURIER, 22, Font.BOLD);
                        
                     doc.add(new Phrase("                        "));
                    doc.add(new Phrase("First Information Report (FIR) ", titleFont));
                    doc.add(new Paragraph("                "));
                    doc.add(new Paragraph());
                    
                    Paragraph p =new Paragraph();
                    p.setIndentationLeft((float)225.0);
                    Image img = Image.getInstance("C:\\Users\\HP\\Desktop\\Practice_Project_Crime_Record\\src\\images\\pdf_icon.png");
                    p.add(img);
                    doc.add(p);
                    
                    p =new Paragraph("Report ID : " + ID,largeBold);
                    p.setIndentationLeft((float)150.0);
                    doc.add(p);

                    doc.add(new Paragraph("            "));
                    doc.add(new Paragraph());

                    doc.add(new Phrase("         "));
                    doc.add(new Phrase("Victim Name        : ", smallBold));
                    doc.add(new Phrase(rs.getString("victim")));
                    doc.add(new Paragraph());
                    
                    doc.add(new Phrase("         "));
                        doc.add(new Phrase("Crime Type         : ", smallBold));
                        doc.add(new Phrase(rs.getString("crimeType")));
                        doc.add(new Paragraph());
                        
                        doc.add(new Phrase("         "));
                        doc.add(new Phrase("Description        : ", smallBold));
                        doc.add(new Phrase(rs.getString("description")));
                        doc.add(new Paragraph());
                        
                        doc.add(new Phrase("         "));
                        doc.add(new Phrase("Crime Place        : ", smallBold));
                        doc.add(new Phrase(rs.getString("crimePlace")));
                        doc.add(new Paragraph());
                        
                        doc.add(new Phrase("         "));
                        doc.add(new Phrase("Possible Suspect   : ", smallBold));
                        doc.add(new Phrase(rs.getString("suspect")));
                        doc.add(new Paragraph());
                        
                        doc.add(new Phrase("         "));
                        doc.add(new Phrase("Details on Suspect : ", smallBold));
                        doc.add(new Phrase(rs.getString("suspectDetails")));
                        doc.add(new Paragraph());
                        
                        doc.add(new Phrase("         "));
                        doc.add(new Phrase("Witness            : ", smallBold));
                        doc.add(new Phrase(rs.getString("witness")));
                        doc.add(new Paragraph());
                        
                        doc.add(new Phrase("         "));
                        doc.add(new Phrase("Witness Statement  : ", smallBold));
                        doc.add(new Phrase(rs.getString("witnessStatement")));
                        doc.add(new Paragraph());
                        
                        doc.close();
                  
                }catch(Exception e){
                    
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_pdfButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seeFIRcopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seeFIRcopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seeFIRcopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seeFIRcopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seeFIRcopy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FIRfilerTxt;
    private com.k33ptoo.App app1;
    private com.k33ptoo.App app2;
    private javax.swing.JLabel complaintFilerTxt;
    private com.k33ptoo.utils.ComponentMoverUtil componentMoverUtil1;
    private com.k33ptoo.utils.ComponentResizerUtil componentResizerUtil1;
    private javax.swing.JLabel consentedByLabel;
    private javax.swing.JLabel crimePlaceLabel;
    private javax.swing.JLabel crimeTypeLabel;
    private javax.swing.JLabel crimeTypeTxt;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel descriptionTxt;
    private javax.swing.JLabel downloadReportLabel;
    private javax.swing.JLabel filedByLabel;
    private javax.swing.JLabel id_noTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pdfButton;
    private javax.swing.JLabel pdfIconLabel;
    private javax.swing.JLabel placeTxt;
    private javax.swing.JLabel reportIDLabel;
    private javax.swing.JLabel ss;
    private javax.swing.JLabel suspectDetailsLabel;
    private javax.swing.JLabel suspectDetailsTxt;
    private javax.swing.JLabel suspectLabel;
    private javax.swing.JLabel suspectTxt;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel victimNameLabel;
    private javax.swing.JLabel victimTxt;
    private javax.swing.JLabel witnessLabel;
    private javax.swing.JLabel witnessStatementLabel;
    private javax.swing.JLabel witnessStatementTxt;
    private javax.swing.JLabel witnessTxt;
    // End of variables declaration//GEN-END:variables
}
