
import java.awt.Color;
import java.awt.Image;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */

public class suspectLocated extends javax.swing.JFrame {

    /**
     * Creates new form suspectLocated
     */
    public static String id;
    public suspectLocated() {
        initComponents();
        addInfoButton.setBackground(Color.WHITE);
        this.setTitle("Suspect Located");
        Image icon = new ImageIcon(this.getClass().getResource("/project_icon.png")).getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        locInfoTxt = new javax.swing.JComboBox<>();
        arrestedByTxt = new javax.swing.JComboBox<>();
        currentlyUnderTxt = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addInfoButton = new javax.swing.JButton();
        locatedFromTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        locInfoTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DB", "PBI", "Private Source" }));
        locInfoTxt.setBorder(null);
        jPanel1.add(locInfoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 141, 135, -1));

        arrestedByTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Investigating Officer", "Special Force", "RAB" }));
        arrestedByTxt.setBorder(null);
        jPanel1.add(arrestedByTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        currentlyUnderTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Police Custody", "CID", "DB", "RAB" }));
        currentlyUnderTxt.setBorder(null);
        jPanel1.add(currentlyUnderTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 135, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Located From");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 104, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Location Information Provided By");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 144, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Arrested By");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Currently Under");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Provide Information for Suspect Capture");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        addInfoButton.setText("Add Info");
        addInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInfoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));
        jPanel1.add(locatedFromTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInfoButtonActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Do you want to add these information on this investigation?", "Select", JOptionPane.YES_NO_OPTION);
        if(x==0){
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/crime record", "root", "");
            
            Statement st = con.createStatement();
            
          
            st.executeUpdate("UPDATE investigation SET locatedFrom='"+locatedFromTxt.getText()+"', locInfoProvidedBy='"+locInfoTxt.getSelectedItem().toString()+"',arrestedBy='"+arrestedByTxt.getSelectedItem().toString()+"',currentlyUnder='"+currentlyUnderTxt.getSelectedItem().toString()+"' WHERE id='"+id+"'   "); 
            
        } catch (Exception e) {
                System.out.println("first item selected");
                System.out.println(id);
        }  
        
        
        String s="y";
        JOptionPane.showMessageDialog(this, "Prime suspect for this case has been located.\nComplaint filer will receive a notification.");
        
        locatedFromTxt.setText("");
        locInfoTxt.setSelectedIndex(0);
        arrestedByTxt.setSelectedIndex(0);
        currentlyUnderTxt.setSelectedIndex(0);
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/crime record", "root", "");
            Statement st = con.createStatement();
            
            st.executeUpdate("UPDATE progress SET suspectLocated='"+s+"' WHERE id='"+id+"'   ");    
        }catch(Exception e){
        }
        IndividualReports.suspectLocatedButton.setEnabled(false);
        IndividualReports.suspectConfessedButton.setEnabled(true);
        }
    }//GEN-LAST:event_addInfoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suspectLocated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suspectLocated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suspectLocated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suspectLocated.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new suspectLocated().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addInfoButton;
    private javax.swing.JComboBox<String> arrestedByTxt;
    private javax.swing.JComboBox<String> currentlyUnderTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> locInfoTxt;
    private javax.swing.JTextField locatedFromTxt;
    // End of variables declaration//GEN-END:variables
}
